name: google_nav_bar_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  badges: ^1.1.1
  flutter:
    sdk: flutter
  google_nav_bar:
    path: ../
  line_icons: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
